### GET request to example server
GET  http://127.0.0.1:8000

###

GET http://127.0.0.1:8000/hello
###

GET http://127.0.0.1:8000/items/1

###
GET http://127.0.0.1:8000/items/1?q=105 OR 1=1

###
POST  http://127.0.0.1:8000/items
Content-Type: application/json

{"name": "air","price": 0}
###